### ISSUE TITLE
关于iissnan主题修改的问题

### ISSUE THREAD

**Issue by skycrown** [iyannik0215/iyannik0215.github.io#1]
博主您好！我看到你的博客中使用了NexT.Pisces主题，且侧边栏是在左侧，我也很喜欢这个主题，无奈一直想将sidebar改到左侧， position: right，但是没成功，不知道你是怎么改的？还有你网站下面的link链接是怎么加上的？我的网站是skycrown.net，期待您的回复，谢谢！ @iyannik0215

**Comment by iyannik0215** [comment]
放在右侧我也是改的这个，没有问题。
```
sidebar:
  # Sidebar Position, available value: left | right
  #position: left
  position: right

  # Sidebar Display, available value:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  Totally remove sidebar including sidebar toggle icon.
  display: post
  #display: always
  #display: hide
  #display: remove
```
友情链接：
```
# title, chinese available
links_title: Link
# links
links:
  Charlotte: http://www.fhg90.com/
  孤独仰望: http://blog.linuser.org/
  蔓舞寻樱: https://hto.io/
```
@skycrown
